# Generated by Django 3.0 on 2019-12-16 12:39

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chaithanya_Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('option1', models.CharField(max_length=300)),
                ('option2', models.CharField(max_length=300)),
                ('option3', models.CharField(max_length=300)),
                ('option4', models.CharField(max_length=300)),
                ('correct_option', models.CharField(max_length=300)),
                ('accuracy_count', models.DecimalField(decimal_places=0, default=0, max_digits=100)),
            ],
        ),
        migrations.CreateModel(
            name='Chaithanya_Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('score', models.IntegerField()),
                ('time', models.IntegerField()),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Narayana_Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('option1', models.CharField(max_length=300)),
                ('option2', models.CharField(max_length=300)),
                ('option3', models.CharField(max_length=300)),
                ('option4', models.CharField(max_length=300)),
                ('correct_option', models.CharField(max_length=300)),
                ('accuracy_count', models.DecimalField(decimal_places=0, default=0, max_digits=100)),
            ],
        ),
        migrations.CreateModel(
            name='Narayana_Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('score', models.IntegerField()),
                ('time', models.IntegerField()),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Narayana', 'Narayana'), ('Chaithanya', 'Chaithanya')], max_length=256, null=True)),
                ('role', models.CharField(blank=True, choices=[('Student', 'Student'), ('College-admin', 'College-admin'), ('Admin', 'Admin')], max_length=256, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
