# Generated by Django 3.0 on 2019-12-16 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_auto_20191216_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chaithanya_submission',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='narayana_submission',
            name='updated',
        ),
    ]
